name: stallone
description: Yet another actor implementation.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta:
  pedantic: # Used until dart 2.14 FutureExtensions
  rxdart: ^0.27.2
  stream_channel: ^2.1.0

dev_dependencies:
  stallone_test_lib:
    path: ../stallone_test_lib
  test:
